# Tek bir dosyanin maksimum boyutu
spring.servlet.multipart.max-file-size=10MB

# multipart/form-data isteginin toplam maksimum boyutu
spring.servlet.multipart.max-request-size=10MB

# StorageProperties'e bind olur; upload klasoru
storage.location=upload-dir