
# Tek bir dosyanin maksimum boyutu
spring.servlet.multipart.max-file-size=128KB

# multipart/form-data isteginin toplam maksimum boyutu
spring.servlet.multipart.max-request-size=128KB

# StorageProperties'e bind olur; upload klasoru
storage.location=upload-dir